global:
  resolve_timeout: 5m

route:
  receiver: google-chat
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: google-chat
    webhook_configs:
      - url_file: /run/secrets/alertmanager-google-chat-webhook
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ['alertname']
